require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: 'comma'

Metrics/BlockLength:
  Max: 35
  ExcludedMethods: [ 'describe' ]

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Layout/LineLength:
  Max: 110

Layout/HashAlignment:
  EnforcedColonStyle: table

RSpec/DescribeClass:
  Enabled: false
